// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "使用邮箱和密码登录，返回 JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"token\\\": \\\"string\\\", \\\"expires_at\\\": \\\"string\\\", \\\"user\\\": {} }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "{ \\\"error\\\": \\\"invalid credentials\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "403": {
                        "description": "{ \\\"error\\\": \\\"email not verified\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前已认证用户的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"user not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册新用户并发送验证邮件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"user_id\\\": \\\"string\\\", \\\"message\\\": \\\"验证邮件已发送，请查收邮箱\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "{ \\\"error\\\": \\\"email already taken\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/resend": {
            "post": {
                "description": "重新发送邮箱验证邮件（有频率限制）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "重发验证邮件",
                "parameters": [
                    {
                        "description": "邮箱",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"message\\\": \\\"如果该邮箱已注册且未验证，验证邮件已发送\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "429": {
                        "description": "{ \\\"error\\\": \\\"resend throttled\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "get": {
                "description": "通过邮件中的 token 验证用户邮箱",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "验证邮箱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证令牌",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证成功页面",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "410": {
                        "description": "{ \\\"error\\\": \\\"token already used\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定游戏的完整状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "查询游戏状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "游戏状态",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/cut": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "歇家或闲二选择切牌位置（37-110）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "切牌（腰牌）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "切牌位置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/dang-jing": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "选择当经牌（三、五、七之一）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "选择当经",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "当经选择",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/deal": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "执行发牌流程，给三个玩家发牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "发牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/discard": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "打出一张手牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "出牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "出牌信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/draw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从公牌顶部起一张牌",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "起牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/ganta": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将手中同名牌加入已有的统组合中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "赶塔",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/pair": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对别人打出的牌进行碰牌操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "碰牌（对/招/泛）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "碰牌信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/pass": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "放弃当前操作（碰牌、和牌等）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "过",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/tong": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "请统阶段，玩家选择统牌或跳过",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "统牌抉择",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "统牌信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/games/{id}/win": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "声明和牌，系统验证手牌是否满足和牌条件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "游戏"
                ],
                "summary": "和牌（胡牌）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "游戏 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"game not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取所有游戏房间列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "列出所有房间",
                "responses": {
                    "200": {
                        "description": "{ \\\"rooms\\\": [] }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新游戏房间，创建者自动加入",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "创建房间",
                "parameters": [
                    {
                        "description": "房间信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"room_id\\\": \\\"string\\\", \\\"room\\\": {} }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据房间 ID 查询房间详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "查询房间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "房间信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"room not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/ai": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向房间添加一个AI玩家（AI自动准备）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "添加AI玩家",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AI 玩家信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"room is full\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"room not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "加入指定房间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "加入房间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "房间信息",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"room is full\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "离开指定房间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "离开房间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/ready": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "设置当前玩家的准备或取消准备状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "设置准备状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "准备状态",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"ok\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"room not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/rooms/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "房主开始游戏，需要房间已满且所有玩家已准备",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "房间"
                ],
                "summary": "开始游戏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房间 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \\\"status\\\": \\\"started\\\", \\\"room_id\\\": \\\"string\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "{ \\\"error\\\": \\\"room is not full\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "{ \\\"error\\\": \\\"room not found\\\" }",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/shuffle": {
            "post": {
                "description": "生成一副打乱的牌，返回牌 ID 栈和完整牌信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工具"
                ],
                "summary": "洗牌",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "随机种子（可选，默认使用当前时间）",
                        "name": "seed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ShuffleResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ShuffleResponse": {
            "type": "object",
            "properties": {
                "seed": {
                    "description": "使用的随机种子",
                    "type": "integer"
                },
                "stack": {
                    "description": "牌 ID 栈（索引 0 为栈顶）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "stack_bottom": {
                    "description": "栈底牌 ID",
                    "type": "integer"
                },
                "stack_top": {
                    "description": "栈顶牌 ID",
                    "type": "integer"
                },
                "tiles": {
                    "description": "完整牌信息（按栈顺序）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tile"
                    }
                }
            }
        },
        "model.Tile": {
            "type": "object",
            "properties": {
                "color": {
                    "$ref": "#/definitions/model.TileColor"
                },
                "id": {
                    "type": "integer"
                },
                "is_flower": {
                    "type": "boolean"
                },
                "name": {
                    "$ref": "#/definitions/model.TileName"
                },
                "numeric": {
                    "description": "数字值(仅数字牌有效, 1-10; 文字牌/别=0)",
                    "type": "integer"
                }
            }
        },
        "model.TileColor": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "ColorBlack",
                "ColorRed"
            ]
        },
        "model.TileName": {
            "type": "string",
            "enum": [
                "乙",
                "二",
                "三",
                "四",
                "五",
                "六",
                "七",
                "八",
                "九",
                "十",
                "孔",
                "己",
                "化",
                "千",
                "土",
                "子",
                "上",
                "大",
                "人",
                "可",
                "知",
                "礼",
                "别"
            ],
            "x-enum-comments": {
                "TileBa": "8",
                "TileEr": "2",
                "TileJiu": "9",
                "TileLiu": "6",
                "TileQi": "7",
                "TileSan": "3",
                "TileShi": "10",
                "TileSi": "4",
                "TileWu": "5",
                "TileYi": "1"
            },
            "x-enum-descriptions": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ],
            "x-enum-varnames": [
                "TileYi",
                "TileEr",
                "TileSan",
                "TileSi",
                "TileWu",
                "TileLiu",
                "TileQi",
                "TileBa",
                "TileJiu",
                "TileShi",
                "TileKong",
                "TileJi",
                "TileHua",
                "TileQian",
                "TileTu",
                "TileZi",
                "TileShang",
                "TileDa",
                "TileRen",
                "TileKe",
                "TileZhi",
                "TileLi",
                "TileBie"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "荆楚花牌 API",
	Description:      "荆楚花牌(花好月圆)游戏服务端 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
